[colors.primary]
foreground = "#ffffff"
background = "#1e1e1e"

[colors.normal]
black   = "#000000"
red     = "#ff0000"
green   = "#00ff00"
yellow  = "#ffff00"
blue    = "#0038eb"
magenta = "#ff00ff"
cyan    = "#00ffff"
white   = "#ffffff"

[cursor]
style = { shape = "Beam", blinking = "Never" }

[font]
size = 8.5

[window]
opacity = 0.9
padding = { x = 5, y = 5 }
