$configDir = $XDG_CONFIG_HOME/hypr/hyprland/presets/bluday

source = $configDir/animations.conf
source = $configDir/colors.conf
source = $configDir/devices.conf
source = $configDir/environmentVariables.conf
source = $configDir/gestures.conf
source = $configDir/keyBindings.conf
source = $configDir/plugins/dynamicCursors.conf
source = $configDir/settings.conf
source = $configDir/startupCommands.conf
source = $configDir/tags.conf
source = $configDir/windowRules.conf
