source = animations.conf
source = colors.conf
source = devices.conf
source = startupCommands.conf
source = environmentVariables.conf
source = gestures.conf
source = keyBindings.conf
source = settings.conf
source = tags.conf
source = windowRules.conf
