windowrule = match:class neovide, tag +code-editor
windowrule = match:class jetbrains-studio, tag +code-editor

windowrule = match:class Thunar, tag +file-browser

windowrule = match:class steam, tag +gaming

windowrule = match:class vlc, tag +media-player

windowrule = match:class Alacritty, tag +terminal

windowrule = match:class firefox, tag +web-browser
windowrule = match:class helium, tag +web-browser
