$configDir = $XDG_CONFIG_HOME/hypr/hyprland

source = $configDir/animations.conf
source = $configDir/colors.conf
source = $configDir/devices.conf
source = $configDir/exec.conf
source = $configDir/environmentVariables.conf
source = $configDir/gestures.conf
source = $configDir/keyBindings.conf
source = $configDir/settings.conf
source = $configDir/windowRules.conf
