$font = Sans

general {
    hide_cursor = false
}

animations {
    enabled = true

    bezier = linear, 1, 1, 0, 0

    animation = fadeIn, 1, 1, linear
    animation = fadeOut, 1, 1, linear
    animation = inputFieldDots, 1, 1, linear
}

background {
    monitor =

    path = screenshot

    blur_passes = 4
}

input-field {
    monitor =
    
    size = 400, 80
    
    outline_thickness = 2
    
    inner_color = rgba(1e1e1ebb)

    outer_color = rgba(323232bb)
    check_color = rgba(484848bb)
    fail_color = rgba(ff0000bb)

    font_color = rgba(ffffff44)
    
    fade_on_empty = false
    
    rounding = 4

    font_family = $font
    
    placeholder_text = Enter password
    
    fail_text = Incorrect password

    dots_size = 0.2
    dots_spacing = 0.4

    position = 0, 0

    halign = center
    valign = center
}

label {
    monitor =
    
    text = $TIME

    font_size = 108
    font_family = $font

    position = 0, 400
    
    halign = center
    valign = center
}

label {
    monitor =
    
    text = cmd[update:60000] date +"%A, %d %B %Y"
    
    font_size = 24
    font_family = $font

    position = 0, 300
    
    halign = center
    valign = center
}
