DEFAULT_APP_LAUNCHER="blu-app-launcher"
DEFAULT_FILE_BROWSER="thunar"
DEFAULT_SCREENSHOTTER="blu-png-screenshot"
DEFAULT_TERMINAL="alacritty"
DEFAULT_WEB_BROWSER="firefox-developer-edition"

EDITOR="neovide"
