QT_AUTO_SCREEN_SCALE_FACTOR=1

QT_QPA_PLATFORM="wayland"
QT_QPA_PLATFORMTHEME="qt5ct"

# Causes newer, already-scaled applications to scale further.
# QT_SCALE_FACTOR=$MONITOR_TARGET_DPI_SCALE_FACTOR

QT_WAYLAND_DISABLE_WINDOWDECORATION=1
