height = 28

justify = "center"

orientation = "horizontal"

position = "bottom"

[[center]]
type = "clock"

# format = "%H:%M"
# format = "%H:%M:%S"
# format = "%Y %B%e — %H:%M"
format = "%Y-%m-%d %H:%M"
# format = "%Y-%m-%d %H:%M:%S"
# format = "%Y-%m-%d %H:%M:%S.%s"

[[end]]
icon_size = 18

type = "tray"

[[end]]
icon_size = 16

type = "battery"

[[start]]
type = "workspaces"
