position = "bottom"

height = 28

[[center]]
type = "clock"

# format = "%H:%M"
# format = "%H:%M:%S"
# format = "%Y %B%e — %H:%M"
format = "%Y-%m-%d %H:%M"
# format = "%Y-%m-%d %H:%M:%S"
# format = "%Y-%m-%d %H:%M:%S.%s"

[[end]]
type = "battery"

show_if = "[ -f /sys/class/power_supply/BAT0 ]"

[[end]]
icon_size = 18

type = "tray"

[[start]]
type = "workspaces"
