$mod      = SUPER
$modShift = $mod SHIFT

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

bind = $mod, B,     exec,                   blu-toggle-ironbar
bind = $mod, C,     killactive
bind = $mod, E,     exec,                   $DEFAULT_FILE_BROWSER
bind = $mod, F,     fullscreen
bind = $mod, J,     togglesplit
bind = $mod, L,     exec,                   hyprlock
bind = $mod, M,     exit
bind = $mod, V,     togglefloating
bind = $mod, P,     pseudo
bind = $mod, Q,     exec,                   $DEFAULT_TERMINAL
bind = $mod, S,     togglespecialworkspace, magic
bind = $mod, Space, exec,                   $DEFAULT_APP_LAUNCHER

bind = $mod, left,  movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up,    movefocus, u
bind = $mod, down,  movefocus, d

bind = $mod, mouse_down, workspace, e+1
bind = $mod, mouse_up,   workspace, e-1

bind = $modShift, 1, movetoworkspace, 1
bind = $modShift, 2, movetoworkspace, 2
bind = $modShift, 3, movetoworkspace, 3
bind = $modShift, 4, movetoworkspace, 4
bind = $modShift, 5, movetoworkspace, 5
bind = $modShift, 6, movetoworkspace, 6
bind = $modShift, 7, movetoworkspace, 7
bind = $modShift, 8, movetoworkspace, 8
bind = $modShift, 9, movetoworkspace, 9
bind = $modShift, 0, movetoworkspace, 10

bind = $modShift, F, fullscreenstate, 1 1
bind = $modShift, S, exec,            blu-png-screenshot # movetoworkspace, special:magic

bind = $modShift, left,  movewindow, l
bind = $modShift, right, movewindow, r
bind = $modShift, up,    movewindow, u
bind = $modShift, down,  movewindow, d

bindel = , XF86AudioRaiseVolume,  exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = , XF86AudioMute,         exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = , XF86AudioMicMute,      exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = , XF86MonBrightnessUp,   exec, brightnessctl -e4 set 20%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl -e4 set 20%-

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow
