windowrule = match:class ^([Nn]eovide|nvim|[Nn]eovim)$,           tag +code-editor
windowrule = match:class ^([Aa]ndroid [Ss]tudio|android-studio)$, tag +code-editor

windowrule = match:class ^([Tt]hunar), tag +file-browser

windowrule = match:class ^([Ss]team), tag +gaming

windowrule = match:class ^(VLC|vlc)$, tag +media-player

windowrule = match:class ^([Aa]lacritty)$, tag +terminal

windowrule = match:class ^([Ff]irefox), tag +web-browser
