music_directory    "$XDG_MUSIC_DIR"
playlist_directory "$XDG_CONFIG_HOME/mpd/playlists"

db_file    "$XDG_CACHE_HOME/mpd/database"
log_file   "$XDG_CACHE_HOME/mpd/log"
pid_file   "$XDG_RUNTIME_DIR/mpd/mpd.pid"
state_file "$XDG_RUNTIME_DIR/mpd/state"

port "6600"

log_level "notice"

restore_paused "yes"

auto_update "yes"

follow_outside_symlinks "yes"
follow_inside_symlinks "yes"

#audio_output {
#   type   "alsa"
#   name   "My ALSA Device"
#   device "hw:0,0"
#}
